name: Continous delivery

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  specs:
    uses: singularities/bso/.github/workflows/specs.yml@main
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: specs
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/singularities/bso:main,ghcr.io/singularities/bso:${{  github.sha }}
          cache-from: type=registry,ref=singularities/bso:main
          cache-to: type=inline
  webhook:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Invoke deployment hook
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"deploy":{"branch":"${{ github.ref_name }}","commit":{"sha":"${{ github.sha }}","message":"deploy"}}}'

