name: Specs

on:
  workflow_call:
env:
  DATABASE_URL: postgres://postgres:password@postgres:5432?pool=10
  RAILS_ENV: test

jobs:
  specs:
    runs-on: ubuntu-latest
    container: ruby:3.1.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bundle exec rails db:test:prepare
          bundle exec rake

